server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
resilience4j:
  bulkhead:
    instances:
      default:
        max-concurrent-calls: 10
  ratelimiter:
    instances:
      default:
        limit-for-period: 2
        limit-refresh-period: 10s
  retry:
    instances:
      est:
        max-attempts: 5
        wait-duration: 1s
        enable-exponential-backoff: true #parecido com fibonacci (wait duration: 1... 3... 5...) +/-
spring:
  application:
    name: thelist-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/thelist_db?useTimezone=true&serverTimezone=America/Sao_Paulo
    username: root 
    password: root
  jackson:
    serialization:
      fail-on-empty-beans: false    
  jpa:
    hibernate:
      ddl-auto: update
    database: MYSQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  flyway:
    url: jdbc:mysql://localhost:3306/thelist_db?useTimezone=true&serverTimezone=America/Sao_Paulo
    user: root
    password: root
  sleuth:
    sampler:
      probability: 1.0
springdoc:
  show-actuator: true
  api-docs:
    path: thelist-service/v3/api-docs