server:
  port: 8080
spring:
  application:
    name: TheList-service
  config:
    import:
    - optional:configserver:http://localhost:8888
  cloud:
    config:
      profile: 
####### CONFIGURATION MYSQL #######
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/todo_list?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
####### CONFIGURATION FLYWAY #######  
  flyway:
    url: jdbc:mysql://localhost:3306
    schemas: todo_list
    user: root
    password: root
    baselineOnMigrate: true
    validateOnMigrate: false        
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
